CREATE TABLE 과목2
	( 과목번호 CHAR(4) NOT NULL PRIMARY KEY
    , 이름 VARCHAR(20) NOT NULL
    , 강의실 CHAR(5) NOT NULL
    , 개설학과 VARCHAR(20) NOT NULL
    , 시수 INT NOT NULL );

CREATE TABLE 학생2
	( 학번 CHAR(4) NOT NULL PRIMARY KEY
    , 이름 VARCHAR(20) NOT NULL
    , 주소 VARCHAR(50) DEFAULT '미정'
    , 학년 INT NOT NULL
    , 나이 INT NULL
    , 성별 CHAR(1) NOT NULL
    , 휴대폰번호 CHAR(13) NULL UNIQUE
    , 소속학과 VARCHAR(20) NULL );
    
DESC 학생2;

CREATE TABLE 수강2
	( 학번 CHAR(4) NOT NULL
    , 과목번호 CHAR(4) NOT NULL
    , 신청날짜 DATE NOT NULL
    , 중간성적 INT NULL DEFAULT 0
    , 기말성적 INT NULL DEFAULT 0
    , 평가학점 CHAR(1) NULL
    , PRIMARY KEY(학번, 과목번호)
    , FOREIGN KEY(학번) REFERENCES 학생2(학번)
    , FOREIGN KEY(과목번호) REFERENCES 과목2(과목번호));
    
INSERT INTO 과목2 SELECT * FROM 과목;
INSERT INTO 학생2 SELECT * FROM 학생;
INSERT INTO 수강2 SELECT * FROM 수강;

ALTER TABLE 학생2
	ADD 등록날짜 DATETIME NOT NULL DEFAULT '2019-12-30' ;

SELECT * FROM 학생2 ;

ALTER TABLE 학생2
	DROP COLUMN 등록날짜 ;

SELECT * FROM 학생2 ;

DROP TABLE 수강2 ;
DROP TABLE 과목2 ;
DROP TABLE 학생2 ;

CREATE USER 'user1'@'127.1.1.1' IDENTIFIED BY '1111' ;
CREATE USER 'user2'@'localhost' IDENTIFIED BY '2222' ;
CREATE USER 'user3'@'192.182.10.2' IDENTIFIED BY '3333' ;
CREATE USER 'user4'@'%' IDENTIFIED BY '4444' ;

SELECT host, user FROM mysql.user ;

GRANT INSERT, UPDATE, DELETE ON univDB.* TO 'user1'@'127.1.1.1' ;
GRANT ALL ON *.* TO 'user4'@'%' WITH GRANT OPTION ;
GRANT SELECT ON univDB.학생 TO 'user2'@'localhost' ;

REVOKE DELETE ON univDB.* FROM 'user1'@'127.1.1.1' ;

DROP USER 'user1'@'127.1.1.1' ;

CREATE USER 'manager'@'%' IDENTIFIED BY '1234' ;

GRANT ALL ON *.* TO 'manager'@'%' WITH GRANT OPTION ;



